// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps_query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createApp = `-- name: CreateApp :one
INSERT INTO "apps" (
  name, domain, landing_url, logo, client_id, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, name, domain, landing_url, logo, client_id, created_at, created_by, updated_at, updated_by, deactivated_at, deactivated_by, deleted_at, deleted_by
`

type CreateAppParams struct {
	Name       string      `json:"name"`
	Domain     string      `json:"domain"`
	LandingUrl string      `json:"landing_url"`
	Logo       pgtype.Text `json:"logo"`
	ClientID   string      `json:"client_id"`
	CreatedBy  uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateApp(ctx context.Context, arg CreateAppParams) (App, error) {
	row := q.db.QueryRow(ctx, createApp,
		arg.Name,
		arg.Domain,
		arg.LandingUrl,
		arg.Logo,
		arg.ClientID,
		arg.CreatedBy,
	)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.LandingUrl,
		&i.Logo,
		&i.ClientID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeactivatedAt,
		&i.DeactivatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const findAppByClientID = `-- name: FindAppByClientID :one
SELECT app.id, app.name, app.domain, app.landing_url, app.logo, app.client_id, app.created_at, app.created_by, app.updated_at, app.updated_by, app.deactivated_at, app.deactivated_by, app.deleted_at, app.deleted_by, oauth_config.id, oauth_config.client_secret, oauth_config.redirect_uris, oauth_config.success_callback_url, oauth_config.error_callback_url, oauth_config.jwt_algo, oauth_config.jwt_secret_resolver, oauth_config.app_id, oauth_config.created_at, oauth_config.created_by, oauth_config.updated_at, oauth_config.updated_by, oauth_config.deleted_at, oauth_config.deleted_by FROM "apps" AS app
LEFT JOIN "oauth_configs" AS oauth_config ON app.id = oauth_config.app_id
WHERE app.client_id = $1 AND app.deleted_by IS NULL
`

type FindAppByClientIDRow struct {
	App         App         `json:"app"`
	OauthConfig OauthConfig `json:"oauth_config"`
}

func (q *Queries) FindAppByClientID(ctx context.Context, clientID string) (FindAppByClientIDRow, error) {
	row := q.db.QueryRow(ctx, findAppByClientID, clientID)
	var i FindAppByClientIDRow
	err := row.Scan(
		&i.App.ID,
		&i.App.Name,
		&i.App.Domain,
		&i.App.LandingUrl,
		&i.App.Logo,
		&i.App.ClientID,
		&i.App.CreatedAt,
		&i.App.CreatedBy,
		&i.App.UpdatedAt,
		&i.App.UpdatedBy,
		&i.App.DeactivatedAt,
		&i.App.DeactivatedBy,
		&i.App.DeletedAt,
		&i.App.DeletedBy,
		&i.OauthConfig.ID,
		&i.OauthConfig.ClientSecret,
		&i.OauthConfig.RedirectUris,
		&i.OauthConfig.SuccessCallbackUrl,
		&i.OauthConfig.ErrorCallbackUrl,
		&i.OauthConfig.JwtAlgo,
		&i.OauthConfig.JwtSecretResolver,
		&i.OauthConfig.AppID,
		&i.OauthConfig.CreatedAt,
		&i.OauthConfig.CreatedBy,
		&i.OauthConfig.UpdatedAt,
		&i.OauthConfig.UpdatedBy,
		&i.OauthConfig.DeletedAt,
		&i.OauthConfig.DeletedBy,
	)
	return i, err
}
