// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Domain        string      `json:"domain"`
	LandingUrl    string      `json:"landing_url"`
	Logo          pgtype.Text `json:"logo"`
	ClientID      string      `json:"client_id"`
	CreatedAt     time.Time   `json:"created_at"`
	CreatedBy     uuid.UUID   `json:"created_by"`
	UpdatedAt     *time.Time  `json:"updated_at"`
	UpdatedBy     *uuid.UUID  `json:"updated_by"`
	DeactivatedAt *time.Time  `json:"deactivated_at"`
	DeactivatedBy *uuid.UUID  `json:"deactivated_by"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	DeletedBy     *uuid.UUID  `json:"deleted_by"`
}

type OauthConfig struct {
	ID                 uuid.UUID   `json:"id"`
	ClientSecret       string      `json:"client_secret"`
	RedirectUris       []string    `json:"redirect_uris"`
	SuccessCallbackUrl string      `json:"success_callback_url"`
	ErrorCallbackUrl   string      `json:"error_callback_url"`
	JwtAlgo            string      `json:"jwt_algo"`
	JwtSecretResolver  pgtype.Text `json:"jwt_secret_resolver"`
	AppID              uuid.UUID   `json:"app_id"`
	CreatedAt          time.Time   `json:"created_at"`
	CreatedBy          uuid.UUID   `json:"created_by"`
	UpdatedAt          *time.Time  `json:"updated_at"`
	UpdatedBy          *uuid.UUID  `json:"updated_by"`
	DeletedAt          *time.Time  `json:"deleted_at"`
	DeletedBy          *uuid.UUID  `json:"deleted_by"`
}

type Password struct {
	ID             uuid.UUID  `json:"id"`
	HashedPassword string     `json:"hashed_password"`
	CreatedAt      time.Time  `json:"created_at"`
	CreatedBy      uuid.UUID  `json:"created_by"`
	UpdatedAt      *time.Time `json:"updated_at"`
	UpdatedBy      *uuid.UUID `json:"updated_by"`
	DeletedAt      *time.Time `json:"deleted_at"`
	DeletedBy      *uuid.UUID `json:"deleted_by"`
}

type User struct {
	ID            uuid.UUID   `json:"id"`
	Email         string      `json:"email"`
	Name          string      `json:"name"`
	Dp            pgtype.Text `json:"dp"`
	CreatedAt     time.Time   `json:"created_at"`
	CreatedBy     uuid.UUID   `json:"created_by"`
	UpdatedAt     *time.Time  `json:"updated_at"`
	UpdatedBy     *uuid.UUID  `json:"updated_by"`
	DeactivatedAt *time.Time  `json:"deactivated_at"`
	DeactivatedBy *uuid.UUID  `json:"deactivated_by"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	DeletedBy     *uuid.UUID  `json:"deleted_by"`
}
