// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: oauth_query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOauthCall = `-- name: CreateOauthCall :exec
INSERT INTO "oauth_calls" (app_id, code, user_id, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateOauthCallParams struct {
	AppID     uuid.UUID `json:"app_id"`
	Code      string    `json:"code"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateOauthCall(ctx context.Context, arg CreateOauthCallParams) error {
	_, err := q.db.Exec(ctx, createOauthCall,
		arg.AppID,
		arg.Code,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const findOauthCallByCode = `-- name: FindOauthCallByCode :one
SELECT id, app_id, code, user_id, expires_at FROM "oauth_calls" WHERE code = $1 AND expires_at > NOW()
`

func (q *Queries) FindOauthCallByCode(ctx context.Context, code string) (OauthCall, error) {
	row := q.db.QueryRow(ctx, findOauthCallByCode, code)
	var i OauthCall
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.Code,
		&i.UserID,
		&i.ExpiresAt,
	)
	return i, err
}
