// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_config.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOauthInfo = `-- name: CreateOauthInfo :exec
INSERT INTO "oauth_configs" (
  client_secret, redirect_uris, success_callback_url, error_callback_url, 
  jwt_algo, jwt_secret_resolver, jwt_lifetime, refresh_token_lifetime, app_id,
  created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
`

type CreateOauthInfoParams struct {
	ClientSecret         string      `json:"client_secret"`
	RedirectUris         []string    `json:"redirect_uris"`
	SuccessCallbackUrl   string      `json:"success_callback_url"`
	ErrorCallbackUrl     string      `json:"error_callback_url"`
	JwtAlgo              string      `json:"jwt_algo"`
	JwtSecretResolver    pgtype.Text `json:"jwt_secret_resolver"`
	JwtLifetime          string      `json:"jwt_lifetime"`
	RefreshTokenLifetime string      `json:"refresh_token_lifetime"`
	AppID                uuid.UUID   `json:"app_id"`
	CreatedBy            uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateOauthInfo(ctx context.Context, arg CreateOauthInfoParams) error {
	_, err := q.db.Exec(ctx, createOauthInfo,
		arg.ClientSecret,
		arg.RedirectUris,
		arg.SuccessCallbackUrl,
		arg.ErrorCallbackUrl,
		arg.JwtAlgo,
		arg.JwtSecretResolver,
		arg.JwtLifetime,
		arg.RefreshTokenLifetime,
		arg.AppID,
		arg.CreatedBy,
	)
	return err
}
