// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: passwords_query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createPasswordForUser = `-- name: CreatePasswordForUser :exec
INSERT INTO "passwords" (
  hashed_password, created_by
) VALUES (
  $1, $2
)
`

type CreatePasswordForUserParams struct {
	HashedPassword string    `json:"hashed_password"`
	CreatedBy      uuid.UUID `json:"created_by"`
}

func (q *Queries) CreatePasswordForUser(ctx context.Context, arg CreatePasswordForUserParams) error {
	_, err := q.db.Exec(ctx, createPasswordForUser, arg.HashedPassword, arg.CreatedBy)
	return err
}

const findUserPassword = `-- name: FindUserPassword :one
SELECT id, hashed_password, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM "passwords" WHERE created_by = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserPassword(ctx context.Context, createdBy uuid.UUID) (Password, error) {
	row := q.db.QueryRow(ctx, findUserPassword, createdBy)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
