// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateApp(ctx context.Context, arg CreateAppParams) (App, error)
	CreateOauthCall(ctx context.Context, arg CreateOauthCallParams) error
	CreateOauthInfo(ctx context.Context, arg CreateOauthInfoParams) error
	CreatePasswordForUser(ctx context.Context, arg CreatePasswordForUserParams) error
	FindAppByClientID(ctx context.Context, clientID string) (FindAppByClientIDRow, error)
	FindOauthCallByCode(ctx context.Context, code string) (OauthCall, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserPassword(ctx context.Context, createdBy uuid.UUID) (Password, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
