// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_query.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO "sessions" (
  "user_id", "app_id", "refresh_token", "user_ip", "user_agent", "expires_at", "created_by"
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type CreateSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	AppID        uuid.UUID `json:"app_id"`
	RefreshToken string    `json:"refresh_token"`
	UserIp       string    `json:"user_ip"`
	UserAgent    string    `json:"user_agent"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.UserID,
		arg.AppID,
		arg.RefreshToken,
		arg.UserIp,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const findSessionByRefreshTokenAndAppID = `-- name: FindSessionByRefreshTokenAndAppID :one
SELECT id, user_id, app_id, refresh_token, user_ip, user_agent, expires_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM "sessions" WHERE "refresh_token" = $1 AND "app_id" = $2 AND expires_at > CURRENT_TIMESTAMP AND "deleted_at" IS NULL
`

type FindSessionByRefreshTokenAndAppIDParams struct {
	RefreshToken string    `json:"refresh_token"`
	AppID        uuid.UUID `json:"app_id"`
}

func (q *Queries) FindSessionByRefreshTokenAndAppID(ctx context.Context, arg FindSessionByRefreshTokenAndAppIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshTokenAndAppID, arg.RefreshToken, arg.AppID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.RefreshToken,
		&i.UserIp,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
