// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users_query.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, name, dp, created_at, created_by, updated_at, updated_by, deactivated_at, deactivated_by, deleted_at, deleted_by FROM "users" WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Dp,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeactivatedAt,
		&i.DeactivatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const registerUser = `-- name: RegisterUser :one
INSERT INTO "users" (
  id, email, name, created_by
) VALUES (
  $1, $2, $3, $4
) RETURNING id, email, name, dp, created_at, created_by, updated_at, updated_by, deactivated_at, deactivated_by, deleted_at, deleted_by
`

type RegisterUserParams struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRow(ctx, registerUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Dp,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeactivatedAt,
		&i.DeactivatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
