# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run_server:
    cmd: air
  run_db:
    cmd: docker-compose -f ./deps/docker/postgres/docker-compose.yml up -d
  stop_db:
    cmd: docker-compose -f ./deps/docker/postgres/docker-compose.yml down
  run_demo_app:
    cmd: go run demo_app/main.go
  run_demo_app:watch:
    cmd: cd demo_app && air
  migration:generate:
    cmds:
      - |
        echo "please enter the migration name:"
        read migration;
        atlas migrate diff ${migration} --env local --to "file://internal/persistence/schema"
  migration:apply:
    cmd: atlas migrate apply --env local
  migration:rehash:
    cmd: atlas migrate hash --dir "file://internal/persistence/migrations"
  generate:repository:
    cmd: sqlc generate